services:
  webapi:
    build:
      context: .
      dockerfile: spring.Dockerfile
    container_name: webapi
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8080/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 60s
    networks:
      - default

  database:
    build:
      context: postgres
      dockerfile: postgres.Dockerfile
    container_name: database
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 60s

  tests:
    image: mrexpen/planet_olymp_phase1
    container_name: tests
    ports:
      - "8090:8080"
    depends_on:
      webapi:
        condition: service_healthy

    networks:
      - default
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all




volumes:
  database_data:

networks:
  default:
    name: default_network
    driver: bridge